spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /healthcheck


jwt-token:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
