swagger:
  contact:
    name: 'Ivonir Mathias Neto'
    email: "ivonir.mathiasneto@gmail.com"
  app:
    name: FourD Challenge
    version: 1.0.0
    description: Api desenvolvida para desafio técnico da fourd.
  base:
    package: br.com.fourdchallenge.backofficeapi.controllers


spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /healthcheck


jwt-token:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

client-origin: ${CLIENT_ORIGIN}
